### ISSUE TITLE
클라이언트 TableView column에 맞추어 백엔드 dto 스펙 수정

### ISSUE THREAD

**Issue by Queue-ri** [ssginc-be/Pickypal-WMS#44]
### Task
클라이언트에서 파싱 용이하도록 필요한 column만 반환해야 함
**본사 재고 조회 dto를 우선 merge 하여 금일(24-12-03) JavaFX 클라이언트에서 테스트 필요**

- [ ] 본사 재고 조회 dto
- [ ] 지점 재고 조회 dto
- [ ] 본사 입고 조회 dto
- [ ] 본사 출고 조회 dto
- [ ] 지점 발주 조회 dto
- [ ] 지점 재고 부족 상품 조회 dto (지점 발주 등록 fxml)
