### ISSUE TITLE
본사 재고 조회 UI에 api 호출 연결

### ISSUE THREAD

**Issue by Queue-ri** [ssginc-be/Pickypal-WMS#48]
### Task
- [ ] `Authorization` 헤더를 세팅하는 GET request 함수 구현
- [ ] api response용 객체 구현
- [ ] 본사 재고 조회 api 호출해서 ObjectMapper로 dto 역직렬화 ( XXXProperty, ObservableList )
    - [레퍼런스](https://jaeho4646.tistory.com/m/145)
- [ ] dto로 JavaFX TableView 값 적용하기
    - [레퍼런스](https://stackoverflow.com/questions/41424544/how-to-update-value-of-each-row-in-table-view-of-javafx)

**Comment by Queue-ri** [comment]
commit 6bbed32e116c40b9e716696c1fec8222c6fa740c dropped.
