### ISSUE TITLE
client API kit 완성 + response DTO 작성 + 샘플 코드 작성

### ISSUE THREAD

**Issue by Queue-ri** [ssginc-be/Pickypal-WMS#63]
### Task
- [ ] API kit 완성
- [ ] response DTO 작성
- [ ] 샘플 코드 작성
    - 객체 형식의 response
    - 객체 리스트 형식의 response

### Reminder
- @Hyun7en 님이 본사 쪽으로 작업하시므로 해당 파일 우선 구현하여 merge
